apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/deployment.yaml
- backend/service.yaml
- backend/pdb.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/pdb.yaml

images:
- name: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/backend
  newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/backend
  newTag: sha-53b8e0d
- name: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/frontend
  newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/frontend
  newTag: sha-2526fc7

commonLabels:
  app.kubernetes.io/part-of: devops-ia
  environment: production
