apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/deployment.yaml
- backend/service.yaml
- backend/pdb.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/pdb.yaml

images:
- name: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/backend
  newName: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/backend
  newTag: sha-0081eb2
- name: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/frontend
  newName: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/frontend
  newTag: sha-1960a63

commonLabels:
  app.kubernetes.io/part-of: devops-ia
  environment: production
